---
- name: Commit and Push Code, and Run Script
  hosts: localhost
  tasks:
    - name: Add all changes
      git:
        repo: /home/anthonys/Documents/code/RALPH
        add: True
        add_ignore_errors: True

    - name: Commit changes
      command: git commit -m "Committing via Ansible"
      args:
        chdir: /home/anthonys/Documents/code/RALPH

    - name: Push changes to GitHub
      command: git push
      args:
        chdir: /home/anthonys/Documents/code/RALPH

- name: Run script on remote host
  hosts: ralph
  tasks:
    - name: Execute script
      command: /home/ralph/startup.sh