---
- name: Commit and Push Code, and Run Script
  hosts: all
  tasks:
    - name: Commit Changes to Github
      ansible.builtin.shell: cd /home/anthonys/Documents/code/RALPH && git add . && git commit -a -m "Committing via Ansible"
      delegate_to: localhost

    - name: Run script on remote host
      ansible.builtin.shell: ./home/ralph/startup.sh  
      when: ansible_hostname == "ralph"