version: '3'
services:
  ralph:
    image: ros:iron-ros-base
    privileged: true
    network_mode: host
    volumes:
      - /dev/ttyAML0:/dev/ttyAML0
    command: bash -c "apt-get update && apt-get install -y git; git clone https://github.com/Leviac42/RALPH.git /opt/ws_ralph/; sleep 20; source /opt/ros/iron/setup.bash; cd /opt/ws_ralph/ && colcon build --symlink-install; sleep 20; source /opt/ws_ralph/install/setup.bash; ros2 launch motor_controller listener"
